project(TileZed
    VERSION 0.8.1
    DESCRIPTION "Project Zomboid Map Tiles Editor"
    HOMEPAGE_URL "https://theindiestone.com"
    LANGUAGES CXX
)

set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTOUIC ON)

find_package(Lua REQUIRED)

set(TileZed_HDRS
    BuildingEditor/building.h
    BuildingEditor/buildingdocument.h
    BuildingEditor/buildingdocumentmgr.h
    BuildingEditor/buildingeditorwindow.h
    BuildingEditor/buildingfloor.h
    BuildingEditor/buildingfloorsdialog.h
    BuildingEditor/buildingfurnituredock.h
    BuildingEditor/buildingisoview.h
    BuildingEditor/buildingkeyvaluesdialog.h
    BuildingEditor/buildinglayersdock.h
    BuildingEditor/buildingmap.h
    BuildingEditor/buildingobjects.h
    BuildingEditor/buildingorthoview.h
    BuildingEditor/buildingpreferences.h
    BuildingEditor/buildingpreferencesdialog.h
    BuildingEditor/buildingpropertiesdialog.h
    BuildingEditor/buildingreader.h
    BuildingEditor/buildingroomdef.h
    BuildingEditor/buildingtemplates.h
    BuildingEditor/buildingtemplatesdialog.h
    BuildingEditor/buildingtileentryview.h
    BuildingEditor/buildingtiles.h
    BuildingEditor/buildingtilesdialog.h
    BuildingEditor/buildingtilesetdock.h
    BuildingEditor/buildingtiletools.h
    BuildingEditor/buildingtmx.h
    BuildingEditor/buildingtools.h
    BuildingEditor/buildingundoredo.h
    BuildingEditor/buildingwriter.h
    BuildingEditor/categorydock.h
    BuildingEditor/choosebuildingtiledialog.h
    BuildingEditor/choosetemplatesdialog.h
    BuildingEditor/editmodestatusbar.h
    BuildingEditor/embeddedmainwindow.h
    BuildingEditor/fancytabwidget.h
    BuildingEditor/furnituregroups.h
    BuildingEditor/furnitureview.h
    BuildingEditor/horizontallinedelegate.h
    BuildingEditor/imode.h
    BuildingEditor/listofstringsdialog.h
    BuildingEditor/mixedtilesetview.h
    BuildingEditor/newbuildingdialog.h
    BuildingEditor/objecteditmode.h
    BuildingEditor/objecteditmode_p.h
    BuildingEditor/resizebuildingdialog.h
    BuildingEditor/roofhiding.h
    BuildingEditor/roomsdialog.h
    BuildingEditor/simplefile.h
    BuildingEditor/singleton.h
    BuildingEditor/templatefrombuildingdialog.h
    BuildingEditor/tilecategoryview.h
    BuildingEditor/tileeditmode.h
    BuildingEditor/tileeditmode_p.h
    BuildingEditor/utils/hostosinfo.h
    BuildingEditor/utils/styledbar.h
    BuildingEditor/utils/stylehelper.h
    BuildingEditor/welcomemode.h
    ZomboidScene.h
    aboutdialog.h
    abstractobjecttool.h
    abstractoverlay.h
    abstracttiletool.h
    abstracttool.h
    addremovelayer.h
    addremovemapobject.h
    addremovetileset.h
    addtilesetsdialog.h
    automapper.h
    automapperwrapper.h
    automappingmanager.h
    automappingutils.h
    bmpblender.h
    bmpblendview.h
    bmpclipboard.h
    bmpruleview.h
    bmpselectionitem.h
    bmptool.h
    bmptooldialog.h
    brushitem.h
    bucketfilltool.h
    changeimagelayerproperties.h
    changemapobject.h
    changeobjectgroupproperties.h
    changepolygon.h
    changeproperties.h
    changetileselection.h
    checkbuildingswindow.h
    checkmapswindow.h
    clipboardmanager.h
    colorbutton.h
    command.h
    commandbutton.h
    commanddatamodel.h
    commanddialog.h
    commandlineparser.h
    containeroverlaydialog.h
    containeroverlayfile.h
    containeroverlayview.h
    convertorientationdialog.h
    converttolotdialog.h
    createobjecttool.h
    createpackdialog.h
    curbtool.h
    curbtooldialog.h
    documentmanager.h
    edgetool.h
    edgetooldialog.h
    editpolygontool.h
    enflatulatordialog.h
    eraser.h
    erasetiles.h
    fencetool.h
    fencetooldialog.h
    filesystemwatcher.h
    filltiles.h
    imagelayeritem.h
    imagelayerpropertiesdialog.h
    languagemanager.h
    layerdock.h
    layermodel.h
    luaconsole.h
    luamapsdialog.h
    luatable.h
    luatiled.h
    luatiletool.h
    luatooldialog.h
    luatooloptions.h
    luaworlddialog.h
    macsupport.h
    mainwindow.h
    mapbuildings.h
    mapcomposite.h
    mapdocument.h
    mapdocumentactionhandler.h
    mapimagemanager.h
    mapmanager.h
    mapobjectitem.h
    mapobjectmodel.h
    mapreaderinterface.h
    mapscene.h
    mapsdock.h
    mapview.h
    mapwriterinterface.h
    minimap.h
    movelayer.h
    movemapobject.h
    movemapobjecttogroup.h
    movetileset.h
    newmapbinaryfile.h
    newmapdialog.h
    newtilesetdialog.h
    objectgroupitem.h
    objectgrouppropertiesdialog.h
    objectpropertiesdialog.h
    objectsdock.h
    objectselectiontool.h
    objecttypes.h
    objecttypesmodel.h
    offsetlayer.h
    offsetmapdialog.h
    packcompare.h
    packextractdialog.h
    packviewer.h
    painttilelayer.h
    picktiletool.h
    pluginmanager.h
    preferences.h
    preferencesdialog.h
    propertiesdialog.h
    propertiesmodel.h
    propertiesview.h
    quickstampmanager.h
    rangeset.h
    rearrangetiles.h
    renamelayer.h
    resizedialog.h
    resizehelper.h
    resizelayer.h
    resizemap.h
    resizemapobject.h
    roomdefecator.h
    roomdefnamedialog.h
    roomdeftool.h
    saveasimagedialog.h
    selectionrectangle.h
    snoweditor.h
    stampbrush.h
    texturepacker.h
    texturepackfile.h
    textureunpacker.h
    threads.h
    tiledapplication.h
    tiledefcompare.h
    tiledefdialog.h
    tiledeffile.h
    tilelayeritem.h
    tilelayerspanel.h
    tilemetainfodialog.h
    tilemetainfomgr.h
    tileoverlaydialog.h
    tileoverlayfile.h
    tilepainter.h
    tileselectionitem.h
    tileselectiontool.h
    tilesetdock.h
    tilesetmanager.h
    tilesetmodel.h
    tilesetstxtfile.h
    tilesetview.h
    tmxmapreader.h
    tmxmapwriter.h
    toolmanager.h
    undocommands.h
    undodock.h
    undoredobuttons.h
    utils.h
    worldeddock.h
    worldlottool.h
    zgriditem.h
    zlevelsdock.h
    zlevelsmodel.h
    zlotmanager.h
    zoomable.h
    zprogress.h
)

set(TileZed_SRCS
    BuildingEditor/building.cpp
    BuildingEditor/buildingdocument.cpp
    BuildingEditor/buildingdocumentmgr.cpp
    BuildingEditor/buildingeditorwindow.cpp
    BuildingEditor/buildingfloor.cpp
    BuildingEditor/buildingfloorsdialog.cpp
    BuildingEditor/buildingfurnituredock.cpp
    BuildingEditor/buildingisoview.cpp
    BuildingEditor/buildingkeyvaluesdialog.cpp
    BuildingEditor/buildinglayersdock.cpp
    BuildingEditor/buildingmap.cpp
    BuildingEditor/buildingobjects.cpp
    BuildingEditor/buildingorthoview.cpp
    BuildingEditor/buildingpreferences.cpp
    BuildingEditor/buildingpreferencesdialog.cpp
    BuildingEditor/buildingpropertiesdialog.cpp
    BuildingEditor/buildingreader.cpp
    BuildingEditor/buildingroomdef.cpp
    BuildingEditor/buildingtemplates.cpp
    BuildingEditor/buildingtemplatesdialog.cpp
    BuildingEditor/buildingtileentryview.cpp
    BuildingEditor/buildingtiles.cpp
    BuildingEditor/buildingtilesdialog.cpp
    BuildingEditor/buildingtilesetdock.cpp
    BuildingEditor/buildingtiletools.cpp
    BuildingEditor/buildingtmx.cpp
    BuildingEditor/buildingtools.cpp
    BuildingEditor/buildingundoredo.cpp
    BuildingEditor/buildingwriter.cpp
    BuildingEditor/categorydock.cpp
    BuildingEditor/choosebuildingtiledialog.cpp
    BuildingEditor/choosetemplatesdialog.cpp
    BuildingEditor/editmodestatusbar.cpp
    BuildingEditor/embeddedmainwindow.cpp
    BuildingEditor/fancytabwidget.cpp
    BuildingEditor/furnituregroups.cpp
    BuildingEditor/furnitureview.cpp
    BuildingEditor/horizontallinedelegate.cpp
    BuildingEditor/imode.cpp
    BuildingEditor/listofstringsdialog.cpp
    BuildingEditor/mixedtilesetview.cpp
    BuildingEditor/newbuildingdialog.cpp
    BuildingEditor/objecteditmode.cpp
    BuildingEditor/resizebuildingdialog.cpp
    BuildingEditor/roofhiding.cpp
    BuildingEditor/roomsdialog.cpp
    BuildingEditor/simplefile.cpp
    BuildingEditor/templatefrombuildingdialog.cpp
    BuildingEditor/tilecategoryview.cpp
    BuildingEditor/tileeditmode.cpp
    BuildingEditor/utils/styledbar.cpp
    BuildingEditor/utils/stylehelper.cpp
    BuildingEditor/welcomemode.cpp
    ZomboidScene.cpp
    aboutdialog.cpp
    abstractobjecttool.cpp
    abstracttiletool.cpp
    abstracttool.cpp
    addremovelayer.cpp
    addremovemapobject.cpp
    addremovetileset.cpp
    addtilesetsdialog.cpp
    automapper.cpp
    automapperwrapper.cpp
    automappingmanager.cpp
    automappingutils.cpp
    bmpblender.cpp
    bmpblendview.cpp
    bmpclipboard.cpp
    bmpruleview.cpp
    bmpselectionitem.cpp
    bmptool.cpp
    bmptooldialog.cpp
    brushitem.cpp
    bucketfilltool.cpp
    changeimagelayerproperties.cpp
    changemapobject.cpp
    changeobjectgroupproperties.cpp
    changepolygon.cpp
    changeproperties.cpp
    changetileselection.cpp
    checkbuildingswindow.cpp
    checkmapswindow.cpp
    clipboardmanager.cpp
    colorbutton.cpp
    command.cpp
    commandbutton.cpp
    commanddatamodel.cpp
    commanddialog.cpp
    commandlineparser.cpp
    containeroverlaydialog.cpp
    containeroverlayfile.cpp
    containeroverlayview.cpp
    convertorientationdialog.cpp
    converttolotdialog.cpp
    createobjecttool.cpp
    createpackdialog.cpp
    curbtool.cpp
    curbtooldialog.cpp
    documentmanager.cpp
    edgetool.cpp
    edgetooldialog.cpp
    editpolygontool.cpp
    enflatulatordialog.cpp
    eraser.cpp
    erasetiles.cpp
    fencetool.cpp
    fencetooldialog.cpp
    filesystemwatcher.cpp
    filltiles.cpp
    imagelayeritem.cpp
    imagelayerpropertiesdialog.cpp
    languagemanager.cpp
    layerdock.cpp
    layermodel.cpp
    luaconsole.cpp
    luamapsdialog.cpp
    luatable.cpp
    luatiled.cpp
    luatiletool.cpp
    luatooldialog.cpp
    luatooloptions.cpp
    luaworlddialog.cpp
    main.cpp
    mainwindow.cpp
    mapbuildings.cpp
    mapcomposite.cpp
    mapdocument.cpp
    mapdocumentactionhandler.cpp
    mapimagemanager.cpp
    mapmanager.cpp
    mapobjectitem.cpp
    mapobjectmodel.cpp
    mapscene.cpp
    mapsdock.cpp
    mapview.cpp
    minimap.cpp
    movelayer.cpp
    movemapobject.cpp
    movemapobjecttogroup.cpp
    movetileset.cpp
    newmapbinaryfile.cpp
    newmapdialog.cpp
    newtilesetdialog.cpp
    objectgroupitem.cpp
    objectgrouppropertiesdialog.cpp
    objectpropertiesdialog.cpp
    objectsdock.cpp
    objectselectiontool.cpp
    objecttypes.cpp
    objecttypesmodel.cpp
    offsetlayer.cpp
    offsetmapdialog.cpp
    packcompare.cpp
    packextractdialog.cpp
    packviewer.cpp
    painttilelayer.cpp
    picktiletool.cpp
    pluginmanager.cpp
    preferences.cpp
    preferencesdialog.cpp
    propertiesdialog.cpp
    propertiesmodel.cpp
    propertiesview.cpp
    quickstampmanager.cpp
    rearrangetiles.cpp
    renamelayer.cpp
    resizedialog.cpp
    resizehelper.cpp
    resizelayer.cpp
    resizemap.cpp
    resizemapobject.cpp
    roomdefecator.cpp
    roomdefnamedialog.cpp
    roomdeftool.cpp
    saveasimagedialog.cpp
    selectionrectangle.cpp
    snoweditor.cpp
    stampbrush.cpp
    texturepacker.cpp
    texturepackfile.cpp
    textureunpacker.cpp
    threads.cpp
    tiledapplication.cpp
    tiledefcompare.cpp
    tiledefdialog.cpp
    tiledeffile.cpp
    tilelayeritem.cpp
    tilelayerspanel.cpp
    tilemetainfodialog.cpp
    tilemetainfomgr.cpp
    tileoverlaydialog.cpp
    tileoverlayfile.cpp
    tilepainter.cpp
    tileselectionitem.cpp
    tileselectiontool.cpp
    tilesetdock.cpp
    tilesetmanager.cpp
    tilesetmodel.cpp
    tilesetstxtfile.cpp
    tilesetview.cpp
    tmxmapreader.cpp
    tmxmapwriter.cpp
    toolmanager.cpp
    undodock.cpp
    undoredobuttons.cpp
    utils.cpp
    worldeddock.cpp
    worldlottool.cpp
    zgriditem.cpp
    zlevelsdock.cpp
    zlevelsmodel.cpp
    zlotmanager.cpp
    zoomable.cpp
    zprogress.cpp
    ztilelayergroupitem.cpp

    aboutdialog.ui
    addtilesetsdialog.ui
    commanddialog.ui
    converttolotdialog.ui
    convertorientationdialog.ui
    mainwindow.ui
    newimagelayerdialog.ui
    newmapdialog.ui
    newtilesetdialog.ui
    objectpropertiesdialog.ui
    offsetmapdialog.ui
    preferencesdialog.ui
    propertiesdialog.ui
    resizedialog.ui
    saveasimagedialog.ui
    tiledefdialog.ui
    tilemetainfodialog.ui

    tiled.qrc
)

qt_add_resources(TileZed_SRCS tiled.qrc BuildingEditor/buildingeditor.qrc)

add_executable(TileZed ${TileZed_SRCS} ${TileZed_HDRS} tiled.rc)

target_compile_definitions(TileZed
    PRIVATE
        -DQT_NO_CAST_FROM_ASCII
        -DQT_NO_CAST_TO_ASCII
)

# uic needs to find colorbutton.h
target_include_directories(TileZed
    PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}
        ${LUA_INCLUDE_DIR} # comes from find_package(Lua)
)

target_link_libraries(TileZed PUBLIC
    Qt::Core
    Qt::Gui
    Qt::Widgets
    qtlockedfile
    qtsingleapplication
    worlded
    tolualib
    tiled
    ${LUA_LIBRARIES} # comes from find_package(Lua)
)

INSTALL(TARGETS TileZed DESTINATION ".")

#add_subdirectory(BuildingEditor)
